### ISSUE TITLE
Prevents edits through a forced list of uneditable IDs

### ISSUE THREAD

**Issue by Codixer** [placeAtlas/atlas-2023#1217]
### Describe the solution

Someway for us to lock specific items and tell the user that they have to create a edit request in our discord.

**Comment by AnonymousRandomPerson** [comment]
I have already added a shortlist of specific entries that will be flagged by the submission script for me to review. We should not lock it down completely, as there are plenty of benign changes like paths that can be made.

**Comment by Codixer** [comment]
More or less referring to the title and description only, the paths can still be edited ofc
