### ISSUE TITLE
Please remove duplicates

### ISSUE THREAD

**Issue by insignout** [placeAtlas/atlas-2023#1309]
### Describe the changes

Here is the main atlas entry for PierreShow: https://2023.place-atlas.stefanocoding.me/#3100/239

Here are duplicates, could you remove them:

https://2023.place-atlas.stefanocoding.me/#3118/239
https://2023.place-atlas.stefanocoding.me/#3095/239
https://2023.place-atlas.stefanocoding.me/#1318/26
https://2023.place-atlas.stefanocoding.me/#1257/55

Thank you!

**Comment by insignout** [comment]
@HaneulCheong - I see that you are able to edit web/atlas.json - can you help with the above? Thank you.

**Comment by AnonymousRandomPerson** [comment]
Done.
