### ISSUE TITLE
Morocco and/or 1337 school atlas entries should mention bot usage

### ISSUE THREAD

**Issue by Janmm14** [placeAtlas/atlas-2023#1588]
[1337 Coding School](https://2023.place-atlas.stefanocoding.me/#330/253)
[Morocco](https://2023.place-atlas.stefanocoding.me/#379/253)

just like [Pompompurin](https://2023.place-atlas.stefanocoding.me/#6244/253) or [Shotbow Network](https://2023.place-atlas.stefanocoding.me/#5000/253) got mentions of bots being used for drawing, the 1337 coding school also used bots obviously and got critized for botting. The wiki should mention this.

**Comment by Hans5958** [comment]
It has been decided to discourage the usage of the word "bots" due to it being a charged accusation, with an exception of a few. I don't want to go into the details in case I typed something wrong here, but let me know if you need more info.
