### ISSUE TITLE
Place_PT link update

### ISSUE THREAD

**Issue by EuGostoDeBacalhauu** [placeAtlas/atlas-2023#1590]
### Describe the changes

Hello! I'm here representing Place_PT, we noticed the links in our description are outdated, as we changed communities and we have a discord server now. I'm here to ask if you could update it, thank you so much for your patience and hard work!

New links:
Discord: https://discord.gg/NcbkxWmUAy
Reddit: Place_PT

**Comment by Hans5958** [comment]
Could you please tell the entry ID of it?

**Comment by Hans5958** [comment]
Correspondent responded that the ID is 2821.
