### ISSUE TITLE
Remove #GerVT

### ISSUE THREAD

**Issue by KukkiiNeko** [placeAtlas/atlas-2023#264]
Due to duplicate entry and this one having old/ wrong information, we would like to remove this entry:

`{"id": "831", "name": "#GerVT", "description": "A collaboration Artwork of the german VTubers Jinja, Maakurika, Finstey, MonaEuphelia, Nayami, EveryLunaEver and Himechii", "links": {}, "path": {"110-136": [[144, -368], [144, -347], [160, -347], [161, -342], [176, -342], [178, -342], [181, -339], [179, -340], [177, -339], [176, -337], [178, -336], [178, -335], [178, -333], [185, -333], [186, -335], [210, -335], [210, -341], [203, -341], [203, -357], [182, -357], [182, -368]]}, "center": {"110-136": [169, -355]}},`
 
in row 799. Is this possible?

**Comment by Hans5958** [comment]
It is duplicate to what?

**Comment by KukkiiNeko** [comment]
entry id 830 marks the same place and has the corect description. We accidentally created both entries without knowing

**Comment by AnonymousRandomPerson** [comment]
Done.
