### ISSUE TITLE
Buggy Zooming on Safari iOS

### ISSUE THREAD

**Issue by ihsan6133** [placeAtlas/atlas-2023#375]
### Describe the bug

On iOS Safari, on index webpage, if the entries sidebar is open, and I try to zoom anywhere in the canvas, it doesnt zoom properly, instead it clips to another part of the canvas. I suspect that, the code responsible for zooming the canvas does not take into account whether the sidebar is open or not.

https://github.com/placeAtlas/atlas-2023/assets/69343917/0818aafa-d295-41bd-9f48-b31991f79279

**Comment by Hans5958** [comment]
Related: placeAtlas/atlas-2022#1376

**Comment by Hans5958** [comment]
I have published a fix (or at least an attempt of it) in https://2023.place-atlas.stefanocoding.me/. Please check whether if the issue still persist.

**Comment by ihsan6133** [comment]
It works perfectly! Thank you. I should jave submitted an issue last year itself!
