### ISSUE TITLE
When scrolling around on the map on mobile, leaving the touchscreen opens a description

### ISSUE THREAD

**Issue by huiuiuiuiui** [placeAtlas/atlas-2023#377]
### Describe the bug

When you zoom and scroll the screen on mobile and then end your scrolling (and leave the screen), this leads to the description of the current position being openend. This is unexpected behaviour because I did not choose to open this specific description, which then takes over half of the screen, so it is difficult to choose your sctual goal.

**Comment by Hans5958** [comment]
I have published a fix (or at least an attempt of it) in https://2023.place-atlas.stefanocoding.me/. Please check whether if the issue still persist.

**Comment by huiuiuiuiui** [comment]
Works like a charme, ty for the quick fix :)

**Comment by huiuiuiuiui** [comment]
Works like a charme, ty for the quick fix :)
