### ISSUE TITLE
the "Tribute to Lola" entry needs to go

### ISSUE THREAD

**Issue by einskleineKatze** [placeAtlas/atlas-2023#505]
The Tribute to Lola artwort is by a strong right-wing group from France, who use this image and the name Lola as propaganda against immigrants. Lola's family does not want this and has said so.

**Comment by AnonymousRandomPerson** [comment]
The fact that it made it on the canvas for several hours means that we can't just remove its entry. It was erased from the canvas subsequently, so the entry will only show up at the specific times it is visible on the canvas.
