### ISSUE TITLE
Change "Nijika patting small Bocchi to "Nijika bonking Kita" (wrong drawing, so wrong title)

### ISSUE THREAD

**Issue by ejennsyahmixcel** [placeAtlas/atlas-2023#565]
{
    	"id": 2182,
    	"name": "Nijika bonking Kita",
    	"description": "This is a picture of Nijika Ijichi bonking Ikuyo Kita in her professor mode, possbly because she try to peek into Ryo on the box below. \n\nNijika and Kita is part of Kessoku Band members in the series Bocchi the Rock!.\n\nNijika always cares about her band members as the band leader of Kessoku Band, and with her angelic personality is also dubbed as Archangel of Shimokitazawa.  \nTruly the paragon of human virtue.\n\nIkuyo Kita in the other hand is a Ryo simp and a bright extrovert, her smile (read: Kitaura) is as powerful as The Sun itself. Sometimes is mistaken as a Filipino due to whatever her name meaning goes in Tagalog (and extends to other SEA countries languages like Indonesian and Malay too).\n\nHowever, her closeness with Bocchi made her somehow fusion with Bocchi, hence suddenly the Bocchi hairpin in the left.",
    	"links": {
    		"website": [
    			"https://www.reddit.com/r/ChurchOfNijika/comments/1064rpf/the_nijika_pledge/"
    		],
    		"subreddit": [
    			"BocchiTheRock",
    			"KessokuBand"
    		],
    		"discord": [
    			"bocchi",
    			"kessokuband"
    		]
    	},
    	"path": {
    		"213-235": [
    			[
    				1327,
    				192
    			],
    			[
    				1379,
    				191
    			],
    			[
    				1379,
    				224
    			],
    			[
    				1328,
    				224
    			],
    			[
    				1326,
    				205
    			],
    			[
    				1328,
    				196
    			]
    		]
    	},
    	"center": {
    		"213-235": [
    			1353,
    			208
    		]
    	}
    }

**Comment by AnonymousRandomPerson** [comment]
Adding for next atlas update.
