### ISSUE TITLE
I would like to work on a way to add submitions on the webpage.

### ISSUE THREAD

**Issue by ihsan6133** [placeAtlas/atlas-2023#590]
### Describe the solution

It would be cool if there was a "Submit Entry" option in the website. This need not necessarily add an entry, but be pushed to a queue so that moderators can review it and add it.

**Comment by ihsan6133** [comment]
The user could draw a selection in the canvas and add the details and click submit

**Comment by Hans5958** [comment]
Not sure what you meant here. We gave two buttons to submit it, via Reddit and GitHub, all on the export entry window. Could you explain it more?

**Comment by Codixer** [comment]
If I understand you correctly @ihsan6133, you want the website to manage everything? So there is a queue on the website itself instead of having to push it to the github/reddit sub?

**Comment by ihsan6133** [comment]
yes that is what i meant, sorry for the late reply

**Comment by Codixer** [comment]
With our current code and infrastructure, that isn't possible. Feel free to check the code, the entire project runs with direct js, CSS and HTML files on Netlify. We don't have a database or somewhere to login. But only a single json file: 
https://2023.place-atlas.stefanocoding.me/atlas.json
