### ISSUE TITLE
Final canvas without bot artwork

### ISSUE THREAD

**Issue by SgtJalau** [placeAtlas/atlas-2023#669]
### Describe the solution

I would suggest creating a (seperate) final canvas image without the artwork that was ruined by bots. So like a composition of the different periods (+- 2 hours) where the artwork was still fully intact. Do not give space to the bots and advertisment + not allow ruined/missing artwork at the end. The artwork all deserves their place in the final canvas image.

**Comment by AnonymousRandomPerson** [comment]
We'll be loading in The Final Clean's image once they release it, like we did with last year's atlas.

**Comment by SgtJalau** [comment]
> We'll be loading in The Final Clean's image once they release it, like we did with last year's atlas.

Sadly the "final" released artwork just now is missing a few things like another painting in the picture frame at the bottom. So I suggest a custom composition.
