### ISSUE TITLE
Overlap view is broken

### ISSUE THREAD

**Issue by mxdanger** [placeAtlas/atlas-2023#95]
### Describe the bug

Likely that it wasn’t updated to work with the center 0,0 coordinate system. It’s squished into the top left corner.

**Comment by AnonymousRandomPerson** [comment]
We can probably remove this. There are lots of legitimate reasons that entries will overlap, and the ongoing nature of the atlas in this event means that we aren't inundated with dupes like last year.

**Comment by Hans5958** [comment]
I don't think the overlap view is primarily to discourage overlaps in the first place. Just yet another way to view the canvas.
